language: node_js
node_js:
  - 12
script:
    - eslint 'src/**'
    - npm run test:ci
deploy:
  provider: heroku
  api_key:
    secure: bfac0fea-c581-4d84-bb8b-59fb9b8ceb03
  app: inGaia-square-meter-api
  on:
    repo: RogerioSobrinho/inGaia-square-meter-api
