language: node_js
node_js:
  - 12
script:
    - eslint 'src/**'
    - npm run test:ci
deploy:
  provider: heroku
  api_key:
    secure: ${{ secrets.SECRET_TOKEN }}
  app: inGaia-square-meter-api
  on:
    repo: RogerioSobrinho/inGaia-square-meter-api
